### ISSUE TITLE
Cannot start nuxt:  input.replace is not a function

### ISSUE THREAD

**Issue by glysns** [data-miner00/nuxt-content-template#14]
Cannot start nuxt:  input.replace is not a function                                                   07:02:26

  at normalizeWindowsPath (/C:/izapay/nuxt-content-template-master/node_modules/.pnpm/pathe@1.1.2/node_modules/pathe/dist/shared/pathe.ff20891b.mjs:6:16)
  at normalize (/C:/izapay/nuxt-content-template-master/node_modules/.pnpm/pathe@1.1.2/node_modules/pathe/dist/shared/pathe.ff20891b.mjs:19:10)
  at resolvePath (/C:/izapay/nuxt-content-template-master/node_modules/.pnpm/@nuxt+kit@3.10.3_rollup@4.12.0/node_modules/@nuxt/kit/dist/index.mjs:2311:10)
  at resolveVueI18nConfigInfo (/C:/izapay/nuxt-content-template-master/node_modules/.pnpm/@nuxtjs+i18n@8.1.1_rollup@4.12.0_vue@3.4.20/node_modules/@nuxtjs/i18n/dist/module.mjs:299:30)
  at /C:/izapay/nuxt-content-template-master/node_modules/.pnpm/@nuxtjs+i18n@8.1.1_rollup@4.12.0_vue@3.4.20/node_modules/@nuxtjs/i18n/dist/module.mjs:692:28
  at Array.map (<anonymous>)
  at resolveLayerVueI18nConfigInfo (/C:/izapay/nuxt-content-template-master/node_modules/.pnpm/@nuxtjs+i18n@8.1.1_rollup@4.12.0_vue@3.4.20/node_modules/@nuxtjs/i18n/dist/module.mjs:690:16)
  at setup (/C:/izapay/nuxt-content-template-master/node_modules/.pnpm/@nuxtjs+i18n@8.1.1_rollup@4.12.0_vue@3.4.20/node_modules/@nuxtjs/i18n/dist/module.mjs:1531:38)
  at async normalizedModule (/C:/izapay/nuxt-content-template-master/node_modules/.pnpm/@nuxt+kit@3.10.3_rollup@4.12.0/node_modules/@nuxt/kit/dist/index.mjs:2112:17)
  at async installModule (/C:/izapay/nuxt-content-template-master/node_modules/.pnpm/@nuxt+kit@3.10.3_rollup@4.12.0/node_modules/@nuxt/kit/dist/index.mjs:2415:95)

**Comment by data-miner00** [comment]
Hi @glysns , thanks for reporting the issue. Which version of Node.js are you using? I have tested it out on Node v18.18.2 and Node v20.9.0 for both dev server and static generation and it works fine on my side. Could you provide more info so that I can proceed with the debugging? Thanks

**Comment by data-miner00** [comment]
If you tried to update the dependencies as suggested on the README, unfortunately it will not work anymore. See #12 . For now, the dependencies must be tight with what `package.json` and `pnpm.lock.yml` specifies.
